"""empty message

Revision ID: db9b59fded7a
Revises: None
Create Date: 2016-10-05 14:25:30.969050

"""

# revision identifiers, used by Alembic.
revision = 'db9b59fded7a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata',
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('desc', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('path')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metadata')
    ### end Alembic commands ###
